### ISSUE TITLE
Repeatable crash after typing characters `()(`

### ISSUE THREAD

**Issue by davej** [MadcapJake/language-earl-grey#14]
Steps to recreate:
1. Create a new file in Atom
2. Set syntax to 'Earl Grey'
3. Type the characters `()(`

On typing the third character, Atom will hang every time (for me). No errors, no explicit crash, Atom just stops responding to input. Steps 2 and 3 can be swapped around and it will still cause a crash.

**Comment by MadcapJake** [comment]
I'm thinking this is an infinite loop because of the begin/end function-call rules.  I'll be able to work on this tonight or tomorrow.

**Comment by MadcapJake** [comment]
Give the new update a go.

**Comment by davej** [comment]
Cool, thanks.
